### ISSUE TITLE
gmb-3.0.1-build-2 crashed upon Shewanella export

### ISSUE THREAD

**Issue by kdahlquist** [lmu-bioinformatics/xmlpipedb#28]
I attempted to do a Shewanella export with gmb-3.0.1-build-2 with the Shewanella source files from the 2015 BioDB course.

The source files I used can be found on the "readme" branch under GenMAPP Gene Databases > S. oneidensis > #current > source-files.  See issue #27 for the issue with spaces in names.

I've attached a screenshot of the console window.
![shewanellaexporterror-1](https://cloud.githubusercontent.com/assets/6463867/12281218/09695cc4-b949-11e5-8830-7629b4cb82c9.jpg)
![shewanellaexporterror-2](https://cloud.githubusercontent.com/assets/6463867/12281220/0c985a76-b949-11e5-95ae-43b0fc4fcc4e.jpg)
![shewanellaexporterror-3](https://cloud.githubusercontent.com/assets/6463867/12281221/0e31b300-b949-11e5-8c58-5da3f390bfe8.jpg)
![shewanellaexporterror-4](https://cloud.githubusercontent.com/assets/6463867/12281225/101557ee-b949-11e5-9bde-da90d32417c1.jpg)

**Comment by dondi** [comment]
OK, I will look into this. Seems to be related to a date value, so will start with that.

**Comment by dondi** [comment]
I ran a bottom-up import-export cycle using these source files and did not encounter these exceptions. I wonder if this was a transient problem with the database connection. It is not unusual that one failure then breaks the connection for all other query attempts. This may have to be a “try again” issue to see if the problem comes up with repeated cycles.

**Comment by kdahlquist** [comment]
A Shewanella import/export cycle completed successfully for me this morning.  I will vet the database for #23.  I will close this now.
