### ISSUE TITLE
Revisit naming convention for releases now we are on GitHub

### ISSUE THREAD

**Issue by kdahlquist** [lmu-bioinformatics/xmlpipedb#4]
@dondi has been publishing draft releases of GenMAPP Builder while he has been working on issue #3 .  However, with the second or third update to the same release, it's hard for me to keep track of different versions with the name number.

Maybe we should move to the x.x.x convention used in GRNsight and GitHub so we could have patch releases with unique numbers.

**Comment by dondi** [comment]
Yes, the recent dev cycle has been somewhat unusual because there was a lot more speculative and tentative work than typical. The draft releases had known failures and so I did not see them as being an official “version.”

That is not to say, though, that the individual drafts should still have been uniquely identifiable—I certainly agree with that. For those types of builds, where they are explicitly experimental/exploratory and even possibly dead-ends, we can add a build-number system. Build numbers identify *all* built versions of a product, tentative or not. This is the current industry practice, varying only on how public these build numbers are, and how they look. Safari uses a completely parallel number:

![safari-build-number](https://cloud.githubusercontent.com/assets/382242/9395251/4973fe24-4742-11e5-993a-a3c1d218ee4a.png)
Java attaches the build number to the current version:

![java-build-number](https://cloud.githubusercontent.com/assets/382242/9395277/6545d5dc-4742-11e5-8e02-983db385c3d1.png)

We can look into establishing this if it is viewed to be desirable. I am not immediately familiar with current methods, but I do know that it is completely automated in some way, and just requires some degree of setup to get going.

**Comment by kdahlquist** [comment]
Build numbers sound good, whatever the best practice is for that.

**Comment by kdahlquist** [comment]
Final decision:
#.#.# build #  

where the first number is major version, the second number is an incremental version, the third number is a patch/bug fix and where the build number is independent.

The next official release will be 3.0.0 build n where n > than the last build number.

We will use even numbers for official releases, so the next release after that will be either

3.2.0 build n or 3.0.2 build n where n > the last build number.
